packages:
  NetTime:
    url: https://github.com/dduan/NetTime
    minorVersion: 0.2.2
  TOMLDeserializer:
    url: https://github.com/dduan/TOMLDeserializer
    minorVersion: 0.2.3
name: TOMLDecoder
targets:
  TOMLDecoder:
    type: framework
    path: Sources/TOMLDecoder
    platform: macOS
    settings:
      INFOPLIST_FILE: Resources/Info.plist
    configFiles:
      Debug: Resources/xcconfigs/TOMLDecoder_Debug.xcconfig
      Release: Resources/xcconfigs/TOMLDecoder_Release.xcconfig
    sources: Sources/TOMLDecoder/
    scheme:
      testTargets:
        - TOMLDecoderTests
    dependencies:
      - package: NetTime
      - package: TOMLDeserializer
  TOMLDecoderTests:
    type: bundle.unit-test
    codeSign: false
    platform: macOS
    sources:
      - path: Tests/TOMLDecoderTests
    dependencies:
      - target: TOMLDecoder
    configFiles:
      Debug: Resources/xcconfigs/UniversalFramework_Test.xcconfig
      Release: Resources/xcconfigs/UniversalFramework_Test.xcconfig
